FORMAT: 1A


# Cars API

This is where people are going to get cars and manufacturers. 

## Cars Collection [/cars]

A model for a car, encapsulating the attributes we track for the car
  and foreign key for the manufacturer.


### List All Cars [GET]

+ Response 200 (application/json)

        {
            "1":{
                "horsepower": 201,
                "model": "ilx",
                "price": 31890.0,
                "make": : "acura",
                "year": 2016,
                "id": 1
            },
            "2":{
                "horsepower": 279,
                "model": "rdx",
                "price": 40370.0,
                "make": : "acura",
                "year": 2016,
                "id": 2
            }
        }

## Manufacturer Collection [/manufacturer]
A model for a manufacturer, encapsulating the attributes we track for
  the manufacturer.
  
### List All Manufacturers [GET]

+ Response 200 (application/json)

        {
            "1":{
                "avg_price": 32971.67,
                "id": 1,
                "num_models": 3,                
                "avg_horsepower": 291.33,
                "name": "chrysler",
                "max_car_id":104
            },
            "2":{
                "avg_price": 27965.0,
                "id": 2,
                "num_models": 8,                
                "avg_horsepower": 190.625,
                "name": "honda",
                "max_car_id": 152
            }
        }