FORMAT: 1A


# Cars API

This is where people are going to get cars and manufacturers. 

## API Root [/]

### Retrieve the API Entry Points [GET]

+ Response 200 (application/json)

        {
            'urls': {
                        "cars": "/cars",
                        "manufacturers": "/manufacturers",
                    }
        }


## Cars Collection [/cars]

A model for a car, encapsulating the attributes we track for the car
  and foreign key for the manufacturer.


### List All Cars [GET]

+ Response 200 (application/json)

        {
            "1":{
                "make": "Lamborhini,
                "model": "Centenario",
                "year": 2015,
                "price": 1900000,
                "safety_rating": 3
            },
            "2":{
                "make": "Lamborhini,
                "model": "Huracan",
                "year": 2015,
                "price": 199000,
                "safety_rating": 4
            }
        }

## Manufacturer Collection [/manufacturer]
A model for a manufacturer, encapsulating the attributes we track for
  the manufacturer.
  
### List All Manufacturers [GET]

+ Response 200 (application/json)

        {
            "1":{
                "name": "Lamborhini",
                "country": "Italy",
                "avg_safety_rating": 3,
                "avg_price": 250000,
                "num_models": 6,
            },
            "2":{
                "name": "Ferrari",
                "country": "Italy",
                "avg_safety_rating": 4,
                "avg_price": 265000,
                "num_models": 9,
            }
        }