FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Cars API

This is where people are going to get cars and manufacturers. 

## Cars Collection [/cars]

A model for a car, encapsulating the attributes we track for the car
  and foreign key for the manufacturer.


### List All Cars [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "make_id": 123,
                "make": "asdf",<---
                "model": "Asdf",
                "year": 2015,
                "price": 50000,
                "safety_rating": 3
            }
        ]

## Manufacturer Collection [/manufacturer]
A model for a manufacturer, encapsulating the attributes we track for
  the manufacturer.
  
### List All Manufacturers [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Asdf",
                "country": "USA",
                "avg_safety_rating": 3,
                "avg_price": 50000,
                "num_models": 10,
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }